spring:
  application:
    name: dictionary-patron-service
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:dictionarypatron
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    stream:
      bindings:
        computeWotd-in-0:
          destination: term.queried
          group: wotd-processor
        computeWotd-out-0:
          destination: wotd.updates
        wotdPersist-in-0:
          destination: wotd.updates
          group: wotd-persister
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000

server:
  port: 8082

logging:
  level:
    com.group18.rotionary.dictionarypatron: DEBUG
