spring:
  application:
    name: dictionary-patron-service
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:dictionarypatron
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

  cloud:
    stream:
      bindings:
        recordQuery-in-0:
          destination: term.queried
        computeWotd-in-0:
          destination: term.queried
        computeWotd-out-0:
          destination: word.of.day
        persistWotd-in-0:
          destination: word.of.day
      kafka:
        binder:
          brokers: localhost:9092

logging:
  level:
    com.group18.rotionary.dictionarypatron: DEBUG
