spring:
  application:
    name: rotle-game-service
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:rotlegame
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    stream:
      bindings:
        gameCompleted-out-0:
          destination: game.completed
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8084

logging:
  level:
    com.group18.rotionary.rotlegame: DEBUG
