spring:
  application:
    name: dictionary-analytics-service
  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:dictionaryanalytics
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    function:
      definition: recordQuery;consumeWotdUpdates;consumeGameCompleted
    stream:
      bindings:
        recordQuery-in-0:
          destination: term.queried
          group: query-processor
        consumeWotdUpdates-in-0:
          destination: term.queried
          group: wotd-update-consumer
        consumeGameCompleted-in-0:
          destination: game.completed
          group: game-analytics-consumer
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8082

logging:
  level:
    com.group18.rotionary.dictionaryanalytics: DEBUG
